### ISSUE TITLE
Guzzle version is incompatible with Laravel 8

### ISSUE THREAD

**Issue by mattfletcher** [PHLAK/lifx-client#6]
This package requires no higher than version 6 of Guzzle, but Laravel 8 requires version 7. Any chance of pushing an update that will be compatible with Guzzle 7?

**Comment by PHLAK** [comment]
Yeah, we can get this updated soon.

**Comment by PHLAK** [comment]
Resolved with [v3.0.0](https://github.com/PHLAK/lifx-client/releases/tag/3.0.0)
